project:
  type: book
  output-dir: docs
  
book:
  title:  2022 Annual System-Wide Monitoring Program (SWMP) Report
  subtitle: Guana Tolomato Matanzas National Estuarine Research Reserve
  author:
    - name: Shannon Dunnigan
    - name: Kathryn Petrinec
    - name: J. Silas Tanner
    - name: Nikki Dix
  chapters:
    - index.qmd
    - part: text/background.qmd
      chapters:
      - text/sites.qmd
      - text/collection.qmd
      - text/qaqc.qmd
    - part: text/results.qmd
      chapters:
      - text/environmental.qmd
      - text/nut-indicators.qmd
      - text/misc-bac.qmd
      - text/hurricane-ian.qmd
      - text/hurricane-nicole.qmd
      - text/maintenance.qmd
  appendices: 
    - text/a1-cmecs.qmd
    
  site-url: https://GTMNERR.github.io/2022-swmp-annual-report
  repo-url: https://github.com/GTMNERR/2022-swmp-annual-report
  repo-actions: [edit, source, issue]
  search: true
  favicon: images/friends-logo.png
  sharing: [twitter, facebook]
  reader-mode: true

  page-footer:
      left: |
        Built with <a href="https://quarto.org/">Quarto</a> with data last updated in February 2022.
      right: |
        <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/80x15.png" /></a>This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License.</a>.</a>

bibliography: text/references.bib

freeze: true

filters: 
  - lightbox
lightbox: auto
  
execute:
  echo: false
  code-overflow: wrap
  warning: false
  error: false

link-external-newwindow: false

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
  # pdf:
  #   documentclass: report
  #   toc: true
  #   toc-depth: 3
  #   lof: true
  #   lot: true
