# Welcome {.unnumbered}

This open source report provides a baseline summary of the three longest running components of the System-Wide Monitoring Program (SWMP) at the Guana Tolomato Matanzas National Estuarine Research Reserve: continuous water quality, discrete water quality, and weather through 2022.

## Summary {.unnumbered}

Rainfall patterns this year drove water quality patterns at all stations. Large rainfall events in March, May, and in the fall with Hurricanes Ian and Nicole resulted in low air temperatures, rising water temperatures, and drops in salinity. Late spring through the summer months had very little rain, which increased salinity and chlorophyll *a* levels at all sites. Chlorophyll *a* was especially high at Pine Island, in which record high monthly chlorophyll *a* values were observed for several months. This site also had an annual geometric mean of chlorophyll *a* over the state threshold value of 6.6 $\mu$g/L for the second year in the record (2002-2022).

Hurricanes Ian and Nicole brought lots of rainfall and oxygenated water into the entire GTM estuary along with high water levels. Observing potential recovery within two weeks after the storm revealed that many sites did return to pre-storm values or ranges during both events. Seasonal "king tide" events continue to make hurricane impacts during the fall difficult to interpret for "recovery" as these king tides bring higher than high tides into northeast Florida.

Prior to this year, temperatures at the weather station only fell below -4 °C on two days: January 24, 2003 (for 6.5 hours, the longest duration below this threshold) and December 14, 2010. This year, temperatures fell below -4°C early on the morning of December 25th for 3 hours.

# Citation {.unnumbered}

Dunnigan, S., K. Petrinec, J.S. Tanner, and N. Dix. 2023. Guana Tolomato Matanzas National Estuarine Research Reserve 2022 Annual System-Wide Monitoring Program Report. Guana Tolomato Matanzas National Estuarine Research Reserve, Ponte Vedra Beach, FL

```{=openxml}
<w:p><w:r><w:br w:type="page"/></w:r></w:p>
```
::: callout-important
This report is will be updated in July 2023 after the collected data has undergone the secondary annual quality assurance and quality control (QAQC) process. For more information on the SWMP QAQC process, please visit <http://cdmo.baruch.sc.edu/data/qaqc.cfm>.
:::
